name: java-starter-kit
owner: twdps-labs
environment:
namespace:
cluster:
version: 0.1
replicaCount: 1
#TUNE as required for application
podDisruptionBudget: 20%

labels:
  app: java-starter-kit

styraLabels:
  styra.io/opa-injection: disabled
  styra.io/system: java-starter-kit

initContainerName: dbinit

image:
  repository: twdps/dps-multi-module-starterkit-java
  imagePullPolicy: IfNotPresent
  tag: "latest"

imagePullSecret: docker-hub-pull-secret

resources:
  requests:
    cpu: 150m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

service:
  type: ClusterIP
  port: 8080

#The .Values.environment is computed by the deploy plugin - it returns//uses values like dev, qa, pre, prod etc
ingress:
  pathPrefix: "/java-starter-kit/"
  hosts:
    - java-starter-kit.{{ .Values.namespace }}.{{ .Values.cluster }}.infoarmor.com
    - api.{{ .Values.environment }}.infoarmor.io
    - java-starter-kit.{{ .Values.namespace }}.svc.cluster.local
  gateways:
    - internal-gateway.istio-system
    - istio-system/external-{{ .Values.environment }}-gateway
    - istio-system/internal-{{ .Values.environment }}-gateway
    - mesh

ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  - name: liveness
    containerPort: 8081
    protocol: TCP
  - name: debug
    containerPort: 5005
    protocol: TCP

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8081
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 10

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8081
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

secrets:
  psql:
    name: psql-secret
    username_key: psql-username
    password_key: psql-password


nsAnyVars:
  - name: JAVA_OPTS
    value: -Xmx512m
  - name: SPRING_PROFILE
    value: dpd
  - name: ZIPKIN_ENABLED
    value: "true"
  - name: ZIPKIN_URL
    value: "http://jaeger-collector.istio-system:14268/api/traces"

nsSpecificVars:
  di-dev:
    - name: SPRING_APPLICATION_DATASOURCE_URL
      value: