site_name: dps-multi-module-starterkit-java
site_description: Java API Starter from Template

nav:
  - 'Overview': index.md
  - 'Quick Start': quickstart.md
  - 'Tutorial': tutorial.md
  - 'Reference': reference.md
  - 'Local Kubernetes': running-kubernetes-local.md
  - 'Architecture Decisions':
      - '0001 - Record Decisions': architecture-decisions/0001-record-architecture-decisions.md

#plugins:
#  - techdocs-core
