version: 2.1

orbs:
  secrethub: secrethub/cli@1.0.0
executors:
  build-agent:
    docker:
      - image: circleci/openjdk:11-jdk
  deploy-agent:
    docker:
      - image:  twdps/di-circleci-infra-image:stable

defaults: &defaults
  docker:
    - image: circleci/openjdk:11-jdk
  working_directory: ~/repo
  environment:
    DOCKER_REGISTRY: docker.pkg.github.com/thoughtworks-dps/dps-multi-module-starterkit-java


jobs:
  build:
    executor: build-agent
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "service/build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "service/build.gradle" }}

      - run:
          name: Run tests
          command: ./gradlew test

  publish:
    executor: build-agent
    environment:
      DOCKER_REGISTRY: twdps
      DOCKER_USER: secrethub://twdps/di/svc/dockerhub/username
      DOCKER_PASSWORD: secrethub://twdps/di/svc/dockerhub/password

    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - secrethub/install
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "service/build.gradle" }}
            - v1-dependencies-

      - run:
          name: What's my build number?
          command: echo $CIRCLE_BUILD_NUM

      - run:
          name: Build Image
          command: ./gradlew docker -PdockerRegistry=$DOCKER_REGISTRY -PbuildNumber=$CIRCLE_BUILD_NUM

      - run:
          name: Docker authentication
          shell: secrethub run -- /bin/sh -eo pipefail
          command: |
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_USER --password-stdin

      - run:
          name: Publish Docker Image
          command: ./gradlew dockerPush -PdockerRegistry=$DOCKER_REGISTRY -PbuildNumber=$CIRCLE_BUILD_NUM

workflows:
  version: 2

  build_test_publish:
    jobs:
      - build
      - publish:
          context: twdps-di
          requires:
            - build