version: 2

defaults: &defaults
  docker:
    - image: circleci/openjdk:11-jdk
  working_directory: ~/repo
  environment:
    DOCKER_REGISTRY: docker.pkg.github.com/thoughtworks-dps/dps-multi-module-starterkit-java


jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "service/build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "service/build.gradle" }}

      - run:
          name: Run tests
          command: ./gradlew test

  publish:

    environment:
      GITHUB_TOKEN: secrethub://twdps/di/svc/github/access-token
      GITHUB_USERNAME: secrethub://twdps/di/svc/github/username
      DOCKER_USER: secrethub://twdps/di/svc/github/username
      PAT: secrethub://twdps/di/svc/dockerhub/password
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "service/build.gradle" }}
            - v1-dependencies-

      - run:
          name: What's my build number?
          command: echo $CIRCLE_BUILD_NUM

      - run:
          name: What's my docker env and username?
          command: echo "$DOCKER_REGISTRY:$GITHUB_USERNAME"

      - run:
          name: Docker authentication
          command: |
            echo $PAT | docker login docker.pkg.github.com --username $DOCKER_USER --password-stdin

      - run:
          name: Build Image
          command: ./gradlew docker -PdockerRegistry=docker.pkg.github.com/thoughtworks-dps/dps-multi-module-starterkit-java -PbuildNumber=$CIRCLE_BUILD_NUM

      - run:
          name: Publish Docker Image
          command: ./gradlew dockerPush -PdockerRegistry=docker.pkg.github.com/thoughtworks-dps/dps-multi-module-starterkit-java -PbuildNumber=$CIRCLE_BUILD_NUM

workflows:
  version: 2

  build_test_publish:
    jobs:
      - build
      - publish:
          requires:
            - build