version: '2.1'
services:
  postgres1:
    image: postgres
    hostname: postgres1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: docker
    volumes:
      - ~/docker/volumes/postgres:/var/lib/postgresql/data

  db_init:
    image: twdps/db-init
    environment:
      POSTGRES_URL: "postgres://postgres:docker@postgres1:5432"
      USERNAME: skuser
      DBNAME: skdb
      PASSWORD: localT3st!
    depends_on:
      - postgres1

  starter-java:
    image: tw.dps/starter-java
    hostname: starter
    ports:
      - "8080:8080"
      - "8081:8081"
#    environment:
#    volumes:
    depends_on:
      - postgres1
      - db_init

  Jaeger:
    image: jaegertracing/all-in-one:1.20
    hostname: jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT : "9411"
